name : REINFORCE
config:
  
  # ============== Hyperparameters ==============
  # The learning rate
  learning_rate: 0.1

  # The discount factor
  gamma : 0.99

  # The number of steps used in the estimation of the Q values.
  # When reaching step i+n_step of the episode, the Q value of the state at step i will be updated using the transitions i to i+n_step-1 in memory.
  # Can be 'inf'. In that case, the algorithm will wait until the end of the episode to update the Q values.
  n_steps : inf


  # ============== Exploration ==============
  
  
  # ============== Logging ==============
  do_log_q_values : False
  n_max_q_values_states_to_log : 1
  do_log_actions_chosen : False
