name: n-step SARSA
config:
  # ============== n-step SARSA Hyperparameters ==============
  # The number of steps
  n_steps : 4

  # ============== Hyperparameters ==============
  # The learning rate
  learning_rate: 0.1

  # The discount factor
  gamma : 0.99

  # ============== Q Values initialization ==============
  # The method for initializing the Q values. Either "random", "zeros" or "optimistic".
  method_q_value_initialization : random
  # A typical return value, for giving the algorithm a hint of what to expect, as well as its standard deviation.
  typical_return : 1.0
  typical_return_std : 1.0

  # ============== Exploration ==============
  # The method for the exploratory policy. Either "eps_greedy", "boltzmann", "ucb",
  method_exploration : eps_greedy

  # The UCB constant (if method_exploration is UCB)
  ucb_constant : 2.0

  # The boltzmann temperature (if method_exploration is boltzmann)
  boltzmann_temperature : 1.0

  # The epsilon parameter (if method_exploration is eps_greedy)
  # epsilon : 0.1
  epsilon:
    class_string : "src.schedulers:Exponential"
    start_value : 1.0
    end_value : 0.01
    n_steps : ${n_steps_exploration}
  
  # ============== Logging ==============
  do_log_q_values : False
  n_max_q_values_states_to_log : 1
  do_log_actions_chosen : False
