# Hyperparameters
n_episodes_training : 1000

# Logging
do_wandb : False
wandb_config:
  project : RL for Optimization Research
  entity : rl_for_or
do_tb : True
do_cli : True
do_tqdm : True



# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - task : toy
  - solver : random
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .