name: Facility Location Problem
name_full: Facility Location Problem (${env.config.n_facilities} facilities, ${env.config.facility_sites} facility sites, ${env.config.customer_sites} customer sites)
duration_average: ${env.config.n_facilities}

config:
  
  # The sites, either as a list of coordinates or as an int, in which case the coordinates are randomly generated.
  # In both cases the coordinates have to be in the range [0, 1]².
  customer_sites : 20
  facility_sites : 10

  # Number of facilities to open.
  n_facilities : 4

  # The render delay between each step when rendering the environment.
  delay_render : 1
  show_final_render : True
  show_lp_solution : True

  # Whether to compute the LP solution.
  compute_lp_solution : True