name: knapsack
config:
  # The capacity of the knapsack
  max_weight: 10.0

  # The number of items in the knapsack
  n_items: 10
  
  # The average weight of an item
  moy_poids: 2.0

  # The maximal value of an item
  max_value: 10.0